---
- name: Install and configure nginx and uwsgi in emperor mode and import simple django project
  hosts: ngserv2
  gather_facts: false
  become: yes
  
  roles:
    - { role: install_packages }
    - { role: config_project_env }
    - { role: config_nginx_uwsgi }
    - { role: add_service }
    - { role: start_services }
