---
- name: Install and configure nginx and uwsgi in emperor mode and import simple django project
  hosts: ngserv2
  gather_facts: false
  become: yes
  
  roles:
    - install_packages
    - config_project_env
    - config_nginx_uwsgi
    - add_service
    - start_services
