---
- name: Install and configure nginx and uwsgi in emperor mode and import simple django project
  hosts: ngserv2
  gather_facts: false
  become: yes

  tasks:
  - name: Import roles
    include_role: 
      name: '{{ role_name }}'
    loop:
      - install_packages
      - config_project_env
      - config_nginx_uwsgi
      - add_service
      - start_services
    loop_control:
      loop_var: role_name
    when: ansible_distribution == 'Debian'
